
netscalers: 
  - host: host1.domain
#    port: 443
    user: 'usrNetScaler'
    password: 'password'
    verify_ssl: false
    timeout: 20
#    keep_session: true # default
#    default_labels:
#      - name: nsip
#        value: host1.domain

  - host: host2.domain
    user: 'usrNetScaler'
    password: 'password'
    verify_ssl: false
    timeout: 20
#    default_labels:
#      - name: nsip
#        value: host2.domain
#    proxy:
#      url: http://my.proxy:9101
#      protocol: https

weblisten:
  address: 0.0.0.0
  port: 9259

logger:
  level: info
  facility: syslog

metrics_file: "metrics/*.yml"

