{
 "title": "CITRIX ADC Netscaler Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Hostname",
    "query": {
     "query": "label_values(citrixadc_probe_success, instance)"
    }
   },
   {
    "name": "service",
    "label": "LBC service",
    "query": {
     "query": "label_values(citrixadc_lb_packets_received_total{instance=~\"$instance\",citrixadc_lb_state=\"UP\"}, citrixadc_lb_name)"
    }
   },
   {
    "name": "ssl_service",
    "label": "SSL service",
    "query": {
     "query": "label_values(citrixadc_sslvserver_health{instance=~\"$instance\"}, citrixadc_sslvserver_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Edition",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "citrixadc_bandwidth_licensed{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 15, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "citrixadc_bandwidth_licensed{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "HA Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "citrixadc_ha_available{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Licensed Bandwidth",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "citrixadc_bandwidth_licensed{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "High Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citrixadc_ha_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citrixadc_ha_node_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Last transition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citrixadc_ha_node_start_timestamp{instance=~\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Propagation timeout Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(citrixadc_ha_node_propagation_timeout_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Sync Failure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(citrixadc_ha_node_sync_failure_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citrixadc_probe_success{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citrixadc_cpu_number_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citrixadc_memory_total_available_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Licensed Throughput percent (stacked)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "( citrixadc_ns_rx_mbits_rate {instance=~\"$instance\"} / sum(citrixadc_bandwidth_licensed{instance=~\"$instance\"}) without(edition,version) )",
     "legendFormat": "received"
    },
    {
     "expr": "( citrixadc_ns_tx_mbits_rate {instance=~\"$instance\"} / sum(citrixadc_bandwidth_licensed{instance=~\"$instance\"}) without(edition,version) )",
     "legendFormat": "transmitted"
    },
    {
     "expr": "( (citrixadc_ns_rx_mbits_rate {instance=~\"$instance\"} + citrixadc_ns_tx_mbits_rate {instance=~\"$instance\"}) / sum(citrixadc_bandwidth_licensed{instance=~\"$instance\"}) without(edition,version) )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Licensed Throughput rate (stacked) ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "citrixadc_ns_rx_mbits_rate {instance=~\"$instance\"}",
     "legendFormat": "received"
    },
    {
     "expr": "citrixadc_ns_tx_mbits_rate {instance=~\"$instance\"}",
     "legendFormat": "transmitted"
    },
    {
     "expr": "citrixadc_bandwidth_licensed{instance=~\"$instance\"}",
     "legendFormat": "Licensed Bandwidth"
    }
   ]
  },
  {
   "title": "CPU Utilization Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "citrixadc_packet_cpu_usage_percent{instance=~\"$instance\"}",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Memory Utilization Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "citrixadc_memory_usage_percent{instance=~\"$instance\"}",
     "legendFormat": "mem % used"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "citrixadc_var_partition_used_percent{instance=~\"$instance\"}",
     "legendFormat": "/var"
    },
    {
     "expr": "citrixadc_flash_partition_used_percent{instance=~\"$instance\"}",
     "legendFormat": "/flash"
    }
   ]
  },
  { "title": "Interfaces Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Average In/out Bits by second by interface",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_interface_tot_rx_bytes_total{instance=~\"$instance\"}[2m]) * 8",
     "legendFormat": "In {{ citrixadc_interface_id }}"
    },
    {
     "expr": "rate(citrixadc_interface_tot_tx_bytes_total{instance=~\"$instance\"}[2m]) * 8",
     "legendFormat": "Out {{ citrixadc_interface_id }}"
    }
   ]
  },
  {
   "title": "Instant In/out Bits by second by interface",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "citrixadc_interface_rx_bytes_rate{instance=~\"$instance\"} * 8",
     "legendFormat": "In {{ citrixadc_interface_id }}"
    },
    {
     "expr": "citrixadc_interface_tx_bytes_rate{instance=~\"$instance\"} * 8",
     "legendFormat": "Out {{ citrixadc_interface_id }}"
    }
   ]
  },
  {
   "title": "Multicast Packet by second by interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_interface_tot_multicast_packets_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "Multicast pkt  {{ citrixadc_interface_id }}"
    }
   ]
  },
  {
   "title": "In/out Dropped Pkt by second by Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_interface_err_dropped_rx_packets_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "In {{ citrixadc_interface_id }}"
    },
    {
     "expr": "rate(citrixadc_interface_err_dropped_tx_packets_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "Out {{ citrixadc_interface_id }}"
    }
   ]
  },
  { "title": "IP stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "In/out Bits by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_ip_tot_rx_bytes_total{instance=~\"$instance\"}[2m]) * 8",
     "legendFormat": "In"
    },
    {
     "expr": "rate(citrixadc_ip_tx_bytes_total{instance=~\"$instance\"}[2m]) *8 ",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "In/out Packets by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_ip_tot_rx_bytes_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(citrixadc_ip_tx_bytes_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packet routed by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_ip_tot_routed_packets_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "routed"
    }
   ]
  },
  {
   "title": "packet stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_ip_tot_fragments_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "fragmented"
    },
    {
     "expr": "rate(citrixadc_ip_tot_successful_assembly_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "assembly"
    },
    {
     "expr": "rate(citrixadc_ip_tot_address_lookup_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "lookup"
    },
    {
     "expr": "rate(citrixadc_ip_tot_address_lookup_fail_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "Failed lookup"
    },
    {
     "expr": "rate(citrixadc_ip_tot_udp_fragments_forwarded_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "udp fragments fwd"
    },
    {
     "expr": "rate(citrixadc_ip_tot_tcp_fragments_forwarded_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "tcp fragments fwd"
    },
    {
     "expr": "rate(citrixadc_ip_tot_bad_checksums_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "bad checksum"
    }
   ]
  },
  { "title": "UDP stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "In/out bits by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_udp_tot_rx_bytes_total {instance=~\"$instance\"}[2m])",
     "legendFormat": "In {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_udp_tot_tx_bytes_total {instance=~\"$instance\"}[2m])",
     "legendFormat": "Out {{ instance }}"
    }
   ]
  },
  {
   "title": "In / Out packets by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_udp_tot_rx_packets_total{instance=~\"$instance\"}[2m]) * 8",
     "legendFormat": "In {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_udp_tot_tx_packets_total{instance=~\"$instance\"}[2m]) *8 ",
     "legendFormat": "Out {{ instance }}"
    }
   ]
  },
  {
   "title": "Unknown - bad checksum packets by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_udp_tot_unknown_service_packets_total {instance=~\"$instance\"}[2m]) * 8",
     "legendFormat": "Unknown {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_udp_tot_bad_checksum_packets_total {instance=~\"$instance\"}[2m]) *8 ",
     "legendFormat": "bad checksum {{ instance }}"
    }
   ]
  },
  { "title": "TCP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "In/out bits by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_tcp_tot_rx_bytes_total {instance=~\"$instance\"}[2m]) * 8 ",
     "legendFormat": "In {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_tot_tx_bytes_total{instance=~\"$instance\"}[2m]) * 8",
     "legendFormat": "Out {{ instance }}"
    }
   ]
  },
  {
   "title": "In/out packets by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_tcp_tot_rx_packets_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "In {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_tot_tx_packets_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "Out {{ instance }}"
    }
   ]
  },
  {
   "title": "TCP metrics by second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_tcp_tot_client_connections_opened_total {instance=~\"$instance\"}[2m])",
     "legendFormat": "client opened cnx {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_tot_server_connections_opened_total {instance=~\"$instance\"}[2m])",
     "legendFormat": "server opened cnx {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_tot_syn_total {instance=~\"$instance\"}[2m])",
     "legendFormat": "SYN received {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_tot_client_fin_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "client FIN received {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_tot_server_fin_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "server FIN received {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_tot_syn_probe_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "PROBE {{ instance }}"
    }
   ]
  },
  {
   "title": "TCP \"errors\" packets by second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_tcp_err_full_retransmit_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "full retransmitted {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_err_badchecksum_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "bad chksum {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_err_reset_threshold_total {instance=~\"$instance\"}[2m])",
     "legendFormat": "RESET {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_err_bad_connection_state_total {instance=~\"$instance\"}[2m])",
     "legendFormat": "BAD state {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_err_out_of_window_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "out of window {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_err_syn_dropped_congestion_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "SYN dropped congestion {{ instance }}"
    },
    {
     "expr": "rate(citrixadc_tcp_err_any_port_fail_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "any port fail {{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request,  Response by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_http_tot_requests_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "Requests {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_tot_responses_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "Responses  {{ instance }}"
      }
     ]
    },
    {
     "title": "Request,  Response instant value by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "citrixadc_http_requests_rate{instance=~\"$instance\"}",
       "legendFormat": "Requests {{ instance }}"
      },
      {
       "expr": "citrixadc_http_responses_rate{instance=~\"$instance\"}",
       "legendFormat": "Responses  {{ instance }}"
      }
     ]
    },
    {
     "title": "HTTP request/response by version by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_http_tot_10_requests_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "HTTP 1.0 req {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_tot_11_requests_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "HTTP 1.1 req {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_tot_10_responses_total {instance=~\"$instance\"}[2m])",
       "legendFormat": "HTTP 1.0 response  {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_tot_10_responses_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "HTTP 1.1 response {{ instance }}"
      }
     ]
    },
    {
     "title": "HTTP methods by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_http_tot_gets_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "GET {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_tot_posts_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "POST {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_tot_others_total {instance=~\"$instance\"}[2m])",
       "legendFormat": "others {{ instance }}"
      }
     ]
    },
    {
     "title": "HTTP chunked by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_http_tot_chunked_requests_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "req {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_tot_chunked_responses_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "response {{ instance }}"
      }
     ]
    },
    {
     "title": "HTTP \"errors\" by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_http_err_tot_incomplete_header_packets_total {instance=~\"$instance\"}[2m])",
       "legendFormat": "incomplete header {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_err_tot_server_responses_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "error response {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_err_tot_large_body_packets_total {instance=~\"$instance\"}[2m])",
       "legendFormat": "too large body {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_err_tot_large_chunk_requests_total {instance=~\"$instance\"}[2m])",
       "legendFormat": "too large chunked size {{ instance }}"
      },
      {
       "expr": "rate(citrixadc_http_err_tot_large_content_requests_total {instance=~\"$instance\"}[2m])",
       "legendFormat": "too large content size {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Balacing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Hits/s by LB Service",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 140 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_lb_hits_total{instance=~\"$instance\", citrixadc_lb_state=\"UP\"}[2m])",
       "legendFormat": "{{ citrixadc_lb_name }} {{ citrixadc_lb_type }} In"
      }
     ]
    },
    {
     "title": "percent of members UP for service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(citrixadc_lb_name) (citrixadc_lb_members_up_total{instance=~\"$instance\"})",
       "legendFormat": "client connection {{ citrixadc_lb_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "LB service Stats $service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "repeat": "service",
   "collapsed": true,
   "panels": [
    {
     "title": "requests & responses by second for $service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum( rate(citrixadc_lb_requests_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m]) ) without( citrixadc_lb_state )",
       "legendFormat": "requests {{ citrixadc_lb_name}}"
      },
      {
       "expr": "sum( rate(citrixadc_lb_responses_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m]) ) without( citrixadc_lb_state )",
       "legendFormat": "Responses {{ citrixadc_lb_name}}"
      }
     ]
    },
    {
     "title": "Stats by second for $service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(citrixadc_lb_hits_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m])) without( citrixadc_lb_state )",
       "legendFormat": "Hits"
      },
      {
       "expr": "sum(rate(citrixadc_lb_surge_count_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m]) ) without( citrixadc_lb_state )",
       "legendFormat": "Surge"
      },
      {
       "expr": "sum( rate(citrixadc_lb_tolerable_transactions_count_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m])) without( citrixadc_lb_state )",
       "legendFormat": "Tolerable Transactions"
      },
      {
       "expr": "sum( rate(citrixadc_lb_ttlb_calculated_transactions_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m]) ) without( citrixadc_lb_state )",
       "legendFormat": "Calculated Transactions"
      },
      {
       "expr": "sum( rate(citrixadc_lb_deffered_requests_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m]) ) without( citrixadc_lb_state )",
       "legendFormat": "deffered req"
      },
      {
       "expr": "sum( rate(citrixadc_lb_spillover_count_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m]) ) without( citrixadc_lb_state )",
       "legendFormat": "Spillover"
      },
      {
       "expr": "sum( rate(citrixadc_lb_invalid_response_request_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m]) ) without( citrixadc_lb_state )",
       "legendFormat": "invalid req"
      },
      {
       "expr": "sum( rate(citrixadc_lb_invalid_response_request_dropped_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m])) without( citrixadc_lb_state )",
       "legendFormat": "dropped req"
      },
      {
       "expr": "sum( rate(citrixadc_lb_busy_error_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m]) ) without( citrixadc_lb_state )",
       "legendFormat": "busy error"
      }
     ]
    },
    {
     "title": "Bytes In/Out by sec for $service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(citrixadc_lb_request_bytes_received_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m])) without( citrixadc_lb_state )",
       "legendFormat": "In"
      },
      {
       "expr": "sum( rate(citrixadc_lb_response_bytes_received_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m])) without( citrixadc_lb_state )",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Packet In/Out by sec for $service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum( rate(citrixadc_lb_packets_received_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m]) ) without( citrixadc_lb_state )",
       "legendFormat": "In"
      },
      {
       "expr": "sum(rate(citrixadc_lb_packets_sent_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}[2m])) without( citrixadc_lb_state )",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "current client connection for $service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(citrixadc_lb_current_client_connection_count{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}) without(citrixadc_lb_state)",
       "legendFormat": "client connection {{ citrixadc_lb_name }}"
      }
     ]
    },
    {
     "title": "percent of members UP for $service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(citrixadc_lb_members_up_total{instance=~\"$instance\", citrixadc_lb_name=~\"$service\"}) without(citrixadc_lb_state)",
       "legendFormat": "client connection {{ citrixadc_lb_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "SSL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSL V2 session by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_ssl_tot_tlsv11_sessions_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "TLSv1 session"
      },
      {
       "expr": "rate(citrixadc_ssl_tot_v2_sessions_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "SSLv2 session"
      }
     ]
    },
    {
     "title": "Total SSL session by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_ssl_tot_sessions_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Total SSL encode by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_ssl_tot_encode_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Total SSL crypto usage by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_ssl_crypto_utilization_stat_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Certificate expiration",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 193 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "citrixadc_ssl_cert_days_to_expire{instance=~\"$instance\"}"
      },
      {
       "expr": "(time() + (citrixadc_ssl_cert_days_to_expire{instance=~\"$instance\"} * 86400)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "SSL service Stats $ssl_service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "repeat": "ssl_service",
   "collapsed": true,
   "panels": [
    {
     "title": "SSL Encrypt/Decrypt bytes/s $ssl_service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_sslvserver_decrypt_bytes_total{instance=~\"$instance\", citrixadc_sslvserver_name=~\"$ssl_service\"}[2m])",
       "legendFormat": "decrypt {{ citrixadc_sslvserver_name }}"
      },
      {
       "expr": "rate(citrixadc_sslvserver_encrypt_bytes_total{instance=~\"$instance\", citrixadc_sslvserver_name=~\"$ssl_service\"}[2m])",
       "legendFormat": "encrypt {{ citrixadc_sslvserver_name }}"
      }
     ]
    },
    {
     "title": "SSL new session and hits /s for $ssl_service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_sslvserver_session_new_total{instance=~\"$instance\", citrixadc_sslvserver_name=~\"$ssl_service\"}[2m])",
       "legendFormat": "new  session {{ citrixadc_sslvserver_name }}"
      },
      {
       "expr": "rate(citrixadc_sslvserver_session_hits_total{instance=~\"$instance\", citrixadc_sslvserver_name=~\"$ssl_service\"}[2m])",
       "legendFormat": "hits {{ citrixadc_sslvserver_name }}"
      }
     ]
    },
    {
     "title": "SSL Encrypt/Decrypt bytes/s $ssl_service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_sslvserver_auth_success_total{instance=~\"$instance\", citrixadc_sslvserver_name=~\"$ssl_service\"}[2m])",
       "legendFormat": "auth success {{ citrixadc_sslvserver_name }}"
      },
      {
       "expr": "rate(citrixadc_sslvserver_auth_failure_total{instance=~\"$instance\", citrixadc_sslvserver_name=~\"$ssl_service\"}[2m])",
       "legendFormat": "auth failure {{ citrixadc_sslvserver_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "AAA Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_aaa_auth_success_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "success auth"
      },
      {
       "expr": "rate(citrixadc_aaa_auth_fail_total {instance=~\"$instance\"}[2m])",
       "legendFormat": "failed auth"
      }
     ]
    },
    {
     "title": "Session",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_aaa_tot_sessions_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "Total session"
      },
      {
       "expr": "rate(citrixadc_aaa_tot_sessiontimeout_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "Timeout session"
      },
      {
       "expr": "rate(citrixadc_aaa_tot_tm_sessions_total {instance=~\"$instance\"}[2m])",
       "legendFormat": "TM? session"
      }
     ]
    },
    {
     "title": "ICA",
     "type": "graph",
     "description": "Count of current Basic ICA only connections.\nCount of current SmartAccess ICA connections.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 218 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "citrixadc_aaa_cur_ica_conn {instance=~\"$instance\"}",
       "legendFormat": "SmartAccess ICA"
      },
      {
       "expr": "citrixadc_aaa_cur_ica_only_conn {instance=~\"$instance\"}",
       "legendFormat": "Basic ICA only conn"
      }
     ]
    }
   ]
  }
 ]
}